version: '3.9'
services:
 
  hapi-postgres:
    image: postgres:13
    container_name: hapi-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PASSWORD=hapi
      - POSTGRES_DB=todo
      - POSTGRES_USER=hapi
    volumes:
      - hapi-postgres:/var/lib/postgresql/data

volumes:
  hapi-postgres:
    name: hapi-postgres-db